version: "3"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: dbuser
      POSTGRES_DB: creditdb
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/db/data:/var/lib/postgresql/data
